"""Product Workflow definitions (Task 034): immutable, Product-owned metadata.

A ``WorkflowDefinition`` describes one deterministic Product process: identity, version,
lifecycle, safe input-field metadata and an ORDERED sequence of
``WorkflowStepDefinition``. v1 Steps run strictly in that order (no DAG).

A definition is plain data. It names no Python class, module, import path, callable,
provider, credential or expression: each Step names only a stable ``handler_id``, which
trusted Product composition binds to trusted code (``WorkflowRuntimeRegistry``).
Definitions are never stored, downloaded, generated by a model or created over HTTP.

Side effects are classified with a fixed vocabulary:

* ``read_only``: may be retried a bounded number of times;
* ``governed_write``: performs its effect only through ``ExecutionCoordinator`` and is
  never retried automatically in v1 (``max_attempts`` must be 1).
"""

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, StringConstraints, model_validator

_FROZEN = ConfigDict(frozen=True, extra="forbid")

_DOTTED = r"^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$"
WorkflowId = Annotated[str, StringConstraints(strict=True, max_length=128, pattern=_DOTTED)]
HandlerId = Annotated[str, StringConstraints(strict=True, max_length=128, pattern=_DOTTED)]
StepId = Annotated[str, StringConstraints(strict=True, pattern=r"^[a-z][a-z0-9_]{0,63}$")]
FieldName = Annotated[str, StringConstraints(strict=True, pattern=r"^[a-z][a-z0-9_]{0,63}$")]
Name = Annotated[str, StringConstraints(strict=True, min_length=1, max_length=80)]
Text = Annotated[str, StringConstraints(strict=True, min_length=1, max_length=500)]

MAX_STEPS = 20
MAX_STEP_TIMEOUT_SECONDS = 300
MAX_STEP_ATTEMPTS = 5


class WorkflowCategory(StrEnum):
    """Classification only: a category grants nothing and selects no behaviour."""

    OPERATIONS = "operations"


class WorkflowLifecycle(StrEnum):
    ACTIVE = "active"
    PREVIEW = "preview"
    DEPRECATED = "deprecated"


class StepSideEffect(StrEnum):
    READ_ONLY = "read_only"
    GOVERNED_WRITE = "governed_write"


class CheckpointPolicy(StrEnum):
    """``none``: the Step produces no checkpoint. ``state``: it must produce one (the
    minimal, typed, size-bounded state a later Step needs)."""

    NONE = "none"
    STATE = "state"


class WorkflowInputKind(StrEnum):
    """Input-field kinds: metadata only (validation is the registered typed input model)."""

    TEXT = "text"
    UUID = "uuid"
    DATE = "date"
    BOOLEAN = "boolean"
    INTEGER = "integer"


class WorkflowInputField(BaseModel):
    model_config = _FROZEN

    name: FieldName
    label: Name
    kind: WorkflowInputKind
    required: bool
    description: Text


class WorkflowStepDefinition(BaseModel):
    model_config = _FROZEN

    step_id: StepId
    name: Name
    description: Text
    handler_id: HandlerId
    side_effect: StepSideEffect
    timeout_seconds: int = Field(ge=1, le=MAX_STEP_TIMEOUT_SECONDS)
    max_attempts: int = Field(ge=1, le=MAX_STEP_ATTEMPTS)
    checkpoint_policy: CheckpointPolicy = CheckpointPolicy.NONE

    @model_validator(mode="after")
    def _writes_are_never_retried(self) -> "WorkflowStepDefinition":
        # No Product idempotency proof exists for automatic write retries in v1.
        if self.side_effect is StepSideEffect.GOVERNED_WRITE and self.max_attempts != 1:
            raise ValueError("a governed_write step runs at most once")
        return self


class WorkflowDefinition(BaseModel):
    model_config = _FROZEN

    workflow_id: WorkflowId
    name: Name
    description: Text
    category: WorkflowCategory
    version: int = Field(ge=1, le=10_000)
    lifecycle: WorkflowLifecycle = WorkflowLifecycle.ACTIVE
    inputs: tuple[WorkflowInputField, ...] = ()
    steps: tuple[WorkflowStepDefinition, ...] = Field(min_length=1, max_length=MAX_STEPS)

    @model_validator(mode="after")
    def _unique(self) -> "WorkflowDefinition":
        step_ids = [s.step_id for s in self.steps]
        if len(step_ids) != len(set(step_ids)):
            raise ValueError("duplicate step id")
        names = [f.name for f in self.inputs]
        if len(names) != len(set(names)):
            raise ValueError("duplicate input field")
        return self

    def step(self, step_id: str) -> WorkflowStepDefinition | None:
        return next((s for s in self.steps if s.step_id == step_id), None)

    @property
    def max_duration_seconds(self) -> int:
        """Upper bound of one complete run: every attempt of every Step timing out."""
        return sum(s.timeout_seconds * s.max_attempts for s in self.steps)
