#!/usr/bin/env bash
# CI smoke test of the runnable LOCAL Product demo (Task 030).
#
#   .github/scripts/demo-smoke.sh <api-image> <web-image>
#
# Drives the REAL launcher (scripts/demo.sh: template compose + deployments/demo
# override, generated credentials) and then the Product ONLY through the user-facing Web
# port: Operations Console, BFF health, the canonical 2026-03-03 daily report, Operations
# analysis on the LOCAL-DEMO-ONLY deterministic model, an explicit idempotent ticket and
# its durable command status across a stop/start that keeps PostgreSQL. It also checks
# the credential boundary (only the key hash reaches the API, nothing reaches Web, no key
# in logs or images), the private API/AgentOS, the API's lack of any outbound network,
# and that the demo model is refused in staging/production. The per-run Product key is a
# throwaway generated by the launcher; it is never printed. No model, provider or
# external integration call is made (the API has no route out of its private networks).
set -euo pipefail

API_IMAGE="${1:?usage: demo-smoke.sh <api-image> <web-image>}"
WEB_IMAGE="${2:?usage: demo-smoke.sh <api-image> <web-image>}"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
WORK="$(mktemp -d)"
# The launcher's DEFAULT path, exactly as a person runs it: `up` builds both images itself
# (the supplied tags; the Docker layer cache makes it cheap after the CI build steps).
export DEMO_API_IMAGE="$API_IMAGE" DEMO_WEB_IMAGE="$WEB_IMAGE"
unset DEMO_SKIP_BUILD
export DEMO_PROJECT="cap-demo-smoke" DEMO_WEB_PORT="13081" DEMO_RUNTIME_DIR="$WORK/runtime"
PROJECT="$DEMO_PROJECT"
WEB="http://127.0.0.1:$DEMO_WEB_PORT"
DEMO="$ROOT/scripts/demo.sh"
DATE="2026-03-03"
SUMMARY="Daily operations report for 2026-03-03 (Europe/Berlin).
Orders created: 1. Shipments shipped: 1. Affected orders: 1.
Shipment statuses: failed 1.
Findings: 1.
- critical: shipment_failed (shipment status failed); recommended action: review_failed_shipment.
Inventory: not_included (store_scoped_inventory_query_unavailable)."

compose() {
  docker compose -p "$PROJECT" -f "$ROOT/deployments/template/compose.yaml" \
    -f "$ROOT/deployments/demo/compose.override.yaml" --env-file "$DEMO_RUNTIME_DIR/runtime.env" "$@"
}

cleanup() {
  status=$?
  if [[ "$status" != 0 && -f "$DEMO_RUNTIME_DIR/runtime.env" ]]; then
    compose ps -a || true
    compose logs --no-color 2>&1 | tail -n 200 || true
  fi
  "$DEMO" reset >/dev/null 2>&1 || true
  rm -rf "$WORK"
}
trap cleanup EXIT

step() { printf '\n== %s\n' "$*"; }
fail() { printf 'FAIL: %s\n' "$*" >&2; exit 1; }
status_of() { curl -s -o /dev/null -w '%{http_code}' "$@"; }
value_of() { sed -n "s/^$2=//p" "$1" | head -n 1; }
json() { python3 -c "import json, sys; data = json.load(sys.stdin); $1"; }
api_id() { compose ps -q api; }
web_id() { compose ps -q web; }
write_count() {
  compose exec -T postgres psql -U platform -d platform -tAc \
    "SELECT (SELECT count(*) FROM product.write_commands) || ',' || (SELECT count(*) FROM product.audit_events)"
}

step "./scripts/demo.sh up: one command starts the whole demo"
"$DEMO" up > "$WORK/up.out" 2> "$WORK/up.err" || { cat "$WORK/up.err" >&2; fail "demo up failed"; }
# Evidence that `up` ran its own build path, then became ready (non-secret lines only).
grep -F "demo: building the Product" "$WORK/up.err" || true
grep -qF "demo: building the Product API image ($API_IMAGE)" "$WORK/up.err" \
  || fail "demo up did not build the API image itself"
grep -qF "demo: building the Product Web image ($WEB_IMAGE)" "$WORK/up.err" \
  || fail "demo up did not build the Web image itself"
grep -xF "Commerce AI Product Demo is ready" "$WORK/up.out" || fail "demo up did not report ready"
CREDENTIALS="$DEMO_RUNTIME_DIR/credentials"
KEY="$(value_of "$CREDENTIALS" PRODUCT_API_KEY)"
STORE="$(value_of "$CREDENTIALS" STORE_ID)"
[[ "$KEY" =~ ^demo-product-key-[0-9a-f]{48}$ ]] || fail "unexpected Product API key format"
out="$(cat "$WORK/up.out")"
for expected in "Commerce AI Product Demo is ready" "Operations Console:" "$WEB" \
                "Product API Key:" "$KEY" "Store UUID:" "$STORE" "Demo business date:" "$DATE" \
                "Suggested analysis:" "Analyze operations for $DATE."; do
  grep -qxF -- "$expected" <<< "$out" || fail "launcher output lacks: ${expected//$KEY/<key>}"
done
# The canonical South store of the mock fixture, derived in the image (never hand-copied).
[[ "$STORE" == "$(docker run --rm --network none "$API_IMAGE" python -c '
import sys; sys.path.insert(0, "/app/apps/api")
from app.integrations.commerce.mock import EntityType, canonical_id
print(canonical_id(EntityType.STORE, "shop_south"))')" ]] || fail "store is not the canonical South store"
for secret in "$(value_of "$DEMO_RUNTIME_DIR/runtime.env" OS_SECURITY_KEY)" \
              "$(value_of "$DEMO_RUNTIME_DIR/runtime.env" POSTGRES_PASSWORD)"; do
  grep -qF "$secret" "$WORK/up.out" "$WORK/up.err" && fail "launcher printed a backend secret"
done
echo "demo ready; key, store, date and prompt printed; no backend secret printed"

step "runtime credential files: private, git-ignored location, distinct secrets"
[[ "$(stat -c '%a' "$DEMO_RUNTIME_DIR")" == 700 ]] || fail "runtime dir is not 700"
for file in "$CREDENTIALS" "$DEMO_RUNTIME_DIR/runtime.env"; do
  [[ "$(stat -c '%a' "$file")" == 600 ]] || fail "$(basename "$file") is not 600"
done
OS_KEY="$(value_of "$DEMO_RUNTIME_DIR/runtime.env" OS_SECURITY_KEY)"
PG_PASSWORD="$(value_of "$DEMO_RUNTIME_DIR/runtime.env" POSTGRES_PASSWORD)"
KEY_SHA="$(printf '%s' "$KEY" | sha256sum | cut -d' ' -f1)"
[[ "$KEY" != "$OS_KEY" && ${#OS_KEY} -ge 32 && ${#PG_PASSWORD} -ge 32 ]] || fail "weak or reused secrets"
grep -qF "$KEY" "$DEMO_RUNTIME_DIR/runtime.env" && fail "raw Product key in the Compose env file"
(cd "$ROOT" && git check-ignore -q deployments/demo/.runtime/credentials \
  && git check-ignore -q deployments/demo/.runtime/runtime.env) || fail "runtime files not git-ignored"
[[ -z "$(cd "$ROOT" && git ls-files deployments/demo/.runtime)" ]] || fail "runtime files are tracked"
echo "files 600 in a 700 dir; git-ignored; Product key != OS key"

step "demo configuration: local, mock backend, demo model, Product auth ON, hash only"
api_env="$(docker inspect "$(api_id)" --format '{{json .Config.Env}}')"
web_env="$(docker inspect "$(web_id)" --format '{{json .Config.Env}}')"
for expected in APP_ENVIRONMENT=local APP_BUSINESS_BACKEND=mock APP_DEFAULT_MODEL_PROVIDER=demo \
                APP_PRODUCT_AUTH_MODE=api_key OPENAI_API_KEY= ANTHROPIC_API_KEY=; do
  [[ "$api_env" == *"\"$expected\""* ]] || fail "API env lacks $expected"
done
[[ "$api_env" == *"$KEY_SHA"* ]] || fail "the Product key hash is not in the API auth config"
[[ "$api_env" != *"$KEY"* ]] || fail "raw Product key in the API environment"
[[ "$web_env" != *"$KEY"* && "$web_env" != *"$KEY_SHA"* && "$web_env" != *"$OS_KEY"* \
   && "$web_env" != *"$PG_PASSWORD"* ]] || fail "a secret reached the Web environment"
[[ "$web_env" == *'"PRODUCT_API_ORIGIN=http://api:8000"'* ]] || fail "Web origin not wired"
echo "API: local/mock/demo, api_key auth with the key's SHA-256; Web: no credential"

step "API and AgentOS private; the API has NO outbound network (no model/provider call possible)"
[[ -z "$(docker port "$(api_id)")" ]] || fail "api publishes a host port"
[[ "$(docker port "$(web_id)")" == "3000/tcp -> 127.0.0.1:$DEMO_WEB_PORT" ]] || fail "unexpected Web binding"
[[ "$(docker inspect "$(api_id)" --format '{{range $n, $_ := .NetworkSettings.Networks}}{{$n}} {{end}}')" \
   == "${PROJECT}_database ${PROJECT}_product " ]] || fail "unexpected API networks"
for network in database product; do
  [[ "$(docker network inspect "${PROJECT}_$network" --format '{{.Internal}}')" == true ]] \
    || fail "$network network is not internal"
done
for path in /agents /info /sessions /docs /openapi.json /api/product/agents; do
  [[ "$(status_of -H "Authorization: Bearer $OS_KEY" "$WEB$path")" == 404 ]] || fail "$path reachable via Web"
done
echo "only Web on 127.0.0.1; API on internal networks only; AgentOS not reachable"

step "Operations Console and BFF health through the Web port"
curl -sf "$WEB/" | grep -q "Operations Console" || fail "Operations Console not served"
curl -sf "$WEB/api/product/health" | json '
assert data["status"] == "ok" and data["application"]["environment"] == "local", data
assert data["agent_runtime"]["status"] == "ready", data
print("BFF health 200, environment local, agent runtime ready")'
[[ "$(status_of "$WEB/api/product/operations/reports/daily?store_id=$STORE&business_date=$DATE")" == 401 ]] \
  || fail "report without a key is not 401"
AUTH=(-H "Authorization: Bearer $KEY")

step "daily report through the Web BFF: canonical 2026-03-03 facts"
curl -sf "${AUTH[@]}" "$WEB/api/product/operations/reports/daily?store_id=$STORE&business_date=$DATE" | json '
r = data["report"]; m = r["metrics"]
failed = {c["status"]: c["count"] for c in m["shipment_status_counts"]}["failed"]
assert (r["business_date"], r["timezone"]) == ("2026-03-03", "Europe/Berlin"), r
assert (m["orders_created"], m["shipments_shipped"], m["affected_orders"], failed) == (1, 1, 1, 1), m
assert [(f["severity"], f["code"]) for f in r["findings"]] == [("critical", "shipment_failed")], r
assert r["coverage"]["inventory"] == "not_included", r
print("orders_created=1 shipments_shipped=1 affected_orders=1 failed=1, one critical finding, inventory not_included")'

step "Operations analysis through the Web BFF on the deterministic demo model"
before="$(write_count)"
run() { curl -s -w '\n%{http_code}' "${AUTH[@]}" -X POST -H 'Content-Type: application/json' \
          -d "{\"message\":\"$1\",\"store_id\":\"$STORE\"}" "$WEB/api/product/operations/runs"; }
for message in "Analyze operations for $DATE." "Analyze operations for $DATE and create a ticket."; do
  response="$(run "$message")"
  [[ "$(tail -n1 <<< "$response")" == 200 ]] || fail "analysis answered $(tail -n1 <<< "$response")"
  sed '$d' <<< "$response" | SUMMARY="$SUMMARY" json '
import os
assert data["message"] == os.environ["SUMMARY"], data["message"]
for marker in ("ord_2002", "ship_507", "delivery_failed", "SE000507", "Sample Express",
               "cus_005", "Robin Demo", "source_status", "external_refs"):
    assert marker not in json.dumps(data), marker'
done
[[ "$(write_count)" == "$before" ]] || fail "analysis wrote a command or audit event"
echo "200 with the deterministic summary (twice); read-only even when asked for a ticket"

step "explicit operational ticket through the Web BFF (idempotent)"
IDEMPOTENCY="demo-smoke-$(od -An -N8 -tx1 /dev/urandom | tr -d ' \n')"
ticket() { curl -s -w '\n%{http_code}' "${AUTH[@]}" -X POST -H 'Content-Type: application/json' \
  -H "Idempotency-Key: $IDEMPOTENCY" -d "{\"store_id\":\"$STORE\",\"title\":\"Investigate failed shipment\",\"description\":\"Review the failed shipment found in the demo operations report.\"}" \
  "$WEB/api/product/operations/tickets"; }
first="$(ticket)"
[[ "$(tail -n1 <<< "$first")" == 201 ]] || fail "ticket answered $(tail -n1 <<< "$first")"
ids="$(sed '$d' <<< "$first" | json '
assert (data["status"], data["replayed"], data["persistence_complete"]) == ("verified", False, True), data
print(data["command_id"], data["ticket_id"])')"
COMMAND="${ids% *}"; TICKET="${ids#* }"
replay="$(ticket)"
[[ "$(tail -n1 <<< "$replay")" == 200 ]] || fail "replay answered $(tail -n1 <<< "$replay")"
sed '$d' <<< "$replay" | COMMAND="$COMMAND" TICKET="$TICKET" json '
import os
assert data["replayed"] is True and data["status"] == "verified", data
assert (data["command_id"], data["ticket_id"]) == (os.environ["COMMAND"], os.environ["TICKET"]), data'
command_status() {
  curl -sf "${AUTH[@]}" "$WEB/api/product/operations/tickets/commands?command_id=$COMMAND" \
    | TICKET="$TICKET" json '
import os
assert (data["status"], data["ticket_id"]) == ("verified", os.environ["TICKET"]), data
print("command", data["command_id"], "verified, ticket", data["ticket_id"])'
}
command_status
echo "201 verified, persistence complete; replay 200 with the same ids"

step "./scripts/demo.sh down + up: PostgreSQL kept, the command is still verified"
"$DEMO" down >/dev/null 2>&1 || fail "demo down failed"
[[ -z "$(compose ps -q)" ]] || fail "services still running after down"
"$DEMO" up > "$WORK/up2.out" 2>/dev/null || fail "demo up (restart) failed"
[[ "$(value_of "$CREDENTIALS" PRODUCT_API_KEY)" == "$KEY" ]] || fail "credentials changed on restart"
command_status
echo "same key, same command, same ticket after a full stop/start"

step "no raw Product key in API/Web logs or in the images"
logs="$(docker logs "$(api_id)" 2>&1; docker logs "$(web_id)" 2>&1)"
for secret in "$KEY" "$OS_KEY" "$PG_PASSWORD"; do
  grep -qF "$secret" <<< "$logs" && fail "a secret appears in the API/Web logs"
done
grep -qF "Bearer" <<< "$(docker logs "$(web_id)" 2>&1)" && fail "Web logs contain a credential"
for image in "$API_IMAGE" "$WEB_IMAGE"; do
  docker history --no-trunc "$image" | grep -qF "$KEY" && fail "raw key in $image history"
  docker image inspect "$image" | grep -qF "$KEY" && fail "raw key in $image config"
done
echo "logs and images clean"

step "the demo model is refused in staging and production by the real API image"
for environment in staging production; do
  set +e
  output="$(docker run --rm --read-only --tmpfs /tmp --network none \
    -e APP_ENVIRONMENT="$environment" -e APP_DEFAULT_MODEL_PROVIDER=demo \
    -e APP_PRODUCT_AUTH_MODE=api_key -e APP_COMPANY_ID=ci-demo-company \
    -e APP_PRODUCT_API_KEYS="[{\"key_id\":\"ci\",\"key_sha256\":\"$KEY_SHA\",\"actor_id\":\"ci\"}]" \
    -e APP_BUSINESS_BACKEND=disabled -e OS_SECURITY_KEY="$OS_KEY" -e AGNO_TELEMETRY=false \
    -e APP_DATABASE_URL="postgresql+psycopg://platform:unused@postgres:5432/platform" \
    "$API_IMAGE" 2>&1)"
  code=$?
  set -e
  [[ "$code" != 0 ]] || fail "$environment started with the demo model"
  grep -qF "demo model provider is not allowed in staging/production" <<< "$output" \
    || fail "$environment failed for another reason"
  grep -qF "$OS_KEY" <<< "$output" && fail "startup failure output contains a secret"
  echo "$environment + demo model: API refused (exit $code)"
done

step "./scripts/demo.sh reset removes the demo data and credentials"
"$DEMO" reset >/dev/null 2>&1 || fail "demo reset failed"
[[ ! -e "$DEMO_RUNTIME_DIR" ]] || fail "runtime credentials remain after reset"
[[ -z "$(docker volume ls -q --filter "name=${PROJECT}_postgres-data")" ]] || fail "demo volume remains"

step "demo smoke passed"
