"""Trusted request-scoped context models.

These models are plain Pydantic and independent of FastAPI. They carry *trusted*
backend context only: values are set by server code (an ``ActorResolver``), never
taken from prompts, model output, request bodies, query parameters or arbitrary
client headers.

``ActorContext`` is identity and granted scope. It deliberately has no
"allowed actions": effective authorization will be computed later by the
permission and policy layers, not stored with the identity.
"""

from typing import Annotated, Literal
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field, StringConstraints

ActorType = Literal["user", "api_client", "system_agent"]
Channel = Literal["api", "web", "whatsapp", "system"]

Identifier = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]

_FROZEN = ConfigDict(frozen=True, extra="forbid")


class ActorContext(BaseModel):
    """Who is acting, for which company, and with which granted scope.

    ``company_id`` is the business entity inside this (physically isolated)
    installation. Roles such as manager or admin are ``role_ids``, not actor types.
    """

    model_config = _FROZEN

    actor_id: Identifier
    actor_type: ActorType
    company_id: Identifier
    role_ids: frozenset[Identifier] = frozenset()
    permissions: frozenset[Identifier] = frozenset()
    store_ids: frozenset[Identifier] = frozenset()


class RequestContext(BaseModel):
    """One per inbound request. ``request_id`` is always generated by the backend."""

    model_config = _FROZEN

    request_id: UUID = Field(default_factory=uuid4)
    actor: ActorContext | None = None
    channel: Channel = "api"
    session_id: Identifier | None = None
